

# 配置Mybatis
# 打开mybatis中的debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 设置当改动文件资源的时候，进行系统从新启动
# 设置数据库
spring:
  devtools:
    restart:
      additional-exclude: static/**,public/**
  jpa:
    hibernate:
      ddl-auto: update
