

# 配置Mybatis
# 打开mybatis中的debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.ywmoyu.tool.Mapper
  mapper-locations: classpath:mapper/*Mapper.xml

# 设置当改动文件资源的时候，进行系统从新启动
# 设置数据库
spring:
  devtools:
    restart:
      additional-exclude: static/**,public/**
  datasource:
    url: jdbc:mysql://localhost:3306/transfer?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
